export const USER_ACTION_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_ACTION_REGISTER_ERROR = 'USER_ACTION_REGISTER_ERROR';
export const USER_ACTION_REGISTER_SUCCESS = 'USER_ACTION_REGISTER_SUCCESS';
export const USER_ACTION_LOGIN_REQUEST = 'USER_ACTION_LOGIN_REQUEST';
export const USER_ACTION_LOGIN_ERROR = 'USER_ACTION_LOGIN_ERROR';
export const USER_ACTION_LOGIN_SUCCESS = 'USER_ACTION_LOGIN_SUCCESS';